#jwt
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      #a day
      expiration: 86400000
      #a week
      refresh-token:
        expiration: 604800000

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

