version: '3'
services:
  discovery-server:
    image: nhuansilver3003/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-networks
  api-gateway:
    image: nhuansilver3003/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8765:8765"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
    networks:
      - my-networks

  auth-service:
    image: nhuansilver3003/auth-service:latest
    container_name: auth-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - my-networks
  product-service:
    container_name: product-service
    image: nhuansilver3003/product-service:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - my-networks
networks:
  my-networks: