server:
  port: 8080

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:admin@104.154.236.58:27017/microservice-db

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka