server:
  port: 8080

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.7sopmmd.mongodb.net/microservice-db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka