spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka